name: Semi-Hourly Job Sync
on:
  schedule:
    # This runs twice an hour, at exactly 17 and 47 minutes past the hour
    - cron: '17,47 * * * *' 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Upstream
        run: |
          gh repo sync ${{ github.repository }} --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
